### ISSUE TITLE
self-hosted builds on MicroZed

### ISSUE THREAD

**Issue by radzy** [WindRiver-OpenSourceLabs/wr-core#2]
When trying to build Pulsar Linux on a MicroZed board running Pulsar Linux, the toolchain is not configured appropriately, so the bitbake command fails:

cube-04-11-15-cube-server:~/pulsar/wr-core/build-xilinx-zynq$ bitbake cube-dom-essential
Loading cache: 100% |###########################################| ETA:  00:00:00
Loaded 2 entries from dependency cache.
ERROR: Unable to determine endianness for architecture 'armv7l' | ETA:  --:--:--
ERROR: Please add your architecture to siteinfo.bbclass
ERROR: Failed to parse recipe: /home/builder/pulsar/wr-core/layers/wrlabs-integration/recipes-support/libyaml/libyaml_0.1.6.bb
ERROR: Unable to determine endianness for architecture 'armv7l'
ERROR: Please add your architecture to siteinfo.bbclass

Summary: There were 5 ERROR messages shown, returning a non-zero exit code.

**Comment by jwessel** [comment]
At this time re-compiling the entire OS on the ARM platform using self hosting does not work.  This is a limitation of the oe-core toolchain in oe-core 1.7, and in part this particular package which expects some native component to be x86 based.

It is not clear that this particular problem is fixed in a later version of oe-core.

**Comment by jwessel** [comment]
Will not be implementing until the Yocto Project has such support.
