### ISSUE TITLE
fedorahosted.com has been shutdown -> checksum failures

### ISSUE THREAD

**Issue by jakob-engblom-i** [WindRiver-OpenSourceLabs/wr-core#43]
I just tried to build wr-core today, and I get a number of failures like this:

WARNING: Failed to fetch URL http://zlib.net/pigz/pigz-2.3.3.tar.gz, attempting MIRRORS if available
WARNING: Checksum failure encountered with download of https://fedorahosted.org/releases/x/m/xmlto/xmlto-0.0.26.tar.gz - will attempt other sources if available
WARNING: Renaming /disk2/windriver-pulsar-linux-github/wr-core/build-intel-x86/../downloads/xmlto-0.0.26.tar.gz to /disk2/windriver-pulsar-linux-github/wr-core/build-intel-x86/../downloads/xmlto-0.0.26.tar.gz_bad-checksum_2eca1a89499c232845ffdd61c6368c04

It seems that fedorahosted.com has been shut down: https://fedoraproject.org/wiki/Infrastructure/Fedorahosted-retirement

**Comment by masselstine** [comment]
Failures or warnings? I just tested this and things do fallback to downloads.yoctoproject.org so the fetch is successful despite the warnings.

This is being tracked upstream by bug 11226
https://bugzilla.yoctoproject.org/show_bug.cgi?id=11226

If you are seeing failures and not just warnings we can reopen this but for now I will close this since upstream will have fixes merged shortly.
