### ISSUE TITLE
secure boot question in intel apollo lake

### ISSUE THREAD

**Issue by aaronadlink** [WindRiver-OpenSourceLabs/wr-core#62]
I need put it to where in BSP if i want use our secure boot key .

Thanks.

**Comment by jiazhang0** [comment]
By default, the sample keys are used. Instead, the keys owned by yourself are called the user keys. In order to use the user keys, try to create a template.conf, e.g,

templates/feature/signing-keys/template.conf
SIGNING_MODEL = "user"
MOK_SB_KEYS_DIR = "<path_to_your_keystore>/mok_sb_keys"
UEFI_SB_KEYS_DIR = "<path_to_your_keystore>/uefi_sb_keys"

You can refer to the layout of wr-core/layers/meta-secure-env/files.

**Comment by jiazhang0** [comment]
I just created 2 commits to make you easier to use the user keys created by yourself. Refer to 
https://github.com/WindRiver-OpenSourceLabs/meta-secure-env/commit/6cfe5102073cd374cd64ffc6cea326a5b90f587b
and
https://github.com/WindRiver-OpenSourceLabs/meta-secure-env/commit/53219688d68dcb6b87686167a42fba1ef6d90cc2

**Comment by jiazhang0** [comment]
@aaronadlink do you still have any problem?

**Comment by aaronadlink** [comment]
one more question : UEFI Secure Boot key will not exist on installation image , Right ?
It is only used in the process of creating the installation image , My understanding right?

**Comment by jiazhang0** [comment]
@aaronadlink Correct. Unlike the typical desktop use, meta-secure-env targets to the embedded segment so the private key **NEVER** be available on any image or filesystem.

More specifically, during the process of creating the installation or runtime image, the certificate corresponding to UEFI secure boot key has been compiled into /EFI/BOOT/LockDown.efi available on the fat partition. If UEFI secure boot key is clear in BIOS setup, grub will automatically launch LockDown.efi to enroll the certificate corresponding to UEFI secure boot key and reboot system to make it taking effect on the next boot.

**Comment by aaronadlink** [comment]
ok
thanks.
